### PR TITLE
Update beatmap jshit

### PR DESCRIPTION
**Pull request by gfjaru**
Update url regexp to match osu! newer beatmaps(set) url

Currently supported url:
/b/${BeatmapSetID}
/beatmapset/${BeatmapSetID}
/s/${BeatmapID}
/beatmaps/${BeatmapID}

Sekian, terima gaji.

fjar#1137

### CODE REVIEW

**Comment by troke12** [comment]
anjing yang dipake bukan ripple.js peok

**Comment by gfjaru** [comment]
terus yang mana bego

**Comment by troke12** [comment]
`dist.min.js`

**Comment by gfjaru** [comment]
apa susanya combine terus compress sendiri anjg aowkaowkaw

**Comment by gfjaru** [comment]
bentar gw edit lagi

**Comment by troke12** [comment]
Ye ini gw lagi combine sabar

**Comment by gfjaru** [comment]
Moved, salah file, trok bangsat -> https://github.com/osu-datenshi/hanayo/pull/14

**Pull request closed without merging**
